/**
 * 2D Office Map Editor - File I/O
 */

/**
 * Export map to JSON format
 */
function exportToJSON() {
    const data = {
        version: '1.0',
        name: EditorState.map.name,
        created: new Date().toISOString(),
        config: {
            width: EditorState.map.width,
            height: EditorState.map.height,
            tileSize: EditorState.map.tileSize
        },
        layers: {
            floor: EditorState.layers.floor,
            walls: EditorState.layers.walls,
            furniture: EditorState.layers.furniture,
            decorations: EditorState.layers.decorations
        },
        collision: EditorState.layers.collision
    };

    return JSON.stringify(data, null, 2);
}

/**
 * Import map from JSON string
 */
function importFromJSON(jsonString) {
    try {
        const data = JSON.parse(jsonString);

        // Validate basic structure
        if (!data.config || !data.layers) {
            throw new Error('Invalid map format');
        }

        // Update map config
        EditorState.map.width = data.config.width || 20;
        EditorState.map.height = data.config.height || 15;
        EditorState.map.name = data.name || 'untitled';

        // Update layers
        EditorState.layers.floor = data.layers.floor || createEmptyLayer(EditorState.map.width, EditorState.map.height, 480);
        EditorState.layers.walls = data.layers.walls || createEmptyLayer(EditorState.map.width, EditorState.map.height, -1);
        EditorState.layers.furniture = data.layers.furniture || createEmptyLayer(EditorState.map.width, EditorState.map.height, -1);
        EditorState.layers.decorations = data.layers.decorations || createEmptyLayer(EditorState.map.width, EditorState.map.height, -1);
        EditorState.layers.collision = data.collision || createEmptyLayer(EditorState.map.width, EditorState.map.height, 0);

        // Refresh UI
        setupMapCanvas();
        render();
        updateMapInfo();

        EditorState.hasUnsavedChanges = false;
        updateUnsavedIndicator();

        return true;
    } catch (error) {
        console.error('Failed to import JSON:', error);
        updateStatus('Error: Failed to load map file');
        return false;
    }
}

/**
 * Download map as JSON file
 */
function downloadMapJSON() {
    const json = exportToJSON();
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `${EditorState.map.name || 'map'}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    EditorState.hasUnsavedChanges = false;
    updateUnsavedIndicator();
    updateStatus('Map saved as JSON');
}

/**
 * Load map from file
 */
async function loadMapFromFile(file) {
    try {
        const text = await file.text();
        if (importFromJSON(text)) {
            updateStatus(`Loaded: ${file.name}`);
        }
    } catch (error) {
        console.error('Failed to read file:', error);
        updateStatus('Error: Failed to read file');
    }
}

/**
 * Export map as JavaScript file (compatible with map.js)
 */
function exportToJS() {
    const { width, height, tileSize } = EditorState.map;

    // Find all used tile indices
    const usedTiles = new Set();
    ['floor', 'walls', 'furniture', 'decorations'].forEach(layerName => {
        const layer = EditorState.layers[layerName];
        layer.forEach(row => {
            row.forEach(tile => {
                if (tile >= 0) usedTiles.add(tile);
            });
        });
    });

    // Generate tile constants
    const tileNames = {
        480: 'FLOOR_GRAY',
        481: 'FLOOR_GRAY2',
        640: 'FLOOR_WOOD',
        641: 'FLOOR_WOOD2',
        1: 'PARTITION_T',
        16: 'PARTITION_L',
        33: 'PARTITION_B',
        320: 'DESK_SINGLE',
        304: 'DESK_L',
        305: 'DESK_M',
        306: 'DESK_R',
        432: 'CHAIR_BLUE',
        128: 'SOFA_L',
        129: 'SOFA_M',
        130: 'SOFA_R',
        416: 'TABLE',
        525: 'PLANT',
        461: 'MONITOR',
        510: 'PRINTER'
    };

    let tilesCode = '// Tile Index Constants\nconst TILES = {\n';
    [...usedTiles].sort((a, b) => a - b).forEach(tile => {
        const name = tileNames[tile] || `TILE_${tile}`;
        tilesCode += `    ${name}: ${tile},\n`;
    });
    tilesCode += '};\n\n';

    // Generate layer arrays
    function formatLayer(layer) {
        return '[\n' + layer.map(row =>
            '    [' + row.join(', ') + ']'
        ).join(',\n') + '\n]';
    }

    let code = `/**
 * Map Data - Generated by 2D Office Map Editor
 * Generated: ${new Date().toISOString()}
 */

${tilesCode}
// Map Configuration
const MAP_CONFIG = {
    width: ${width},
    height: ${height},
    tileSize: ${tileSize}
};

// Layer Data
const floorLayer = ${formatLayer(EditorState.layers.floor)};

const wallLayer = ${formatLayer(EditorState.layers.walls)};

const furnitureLayer = ${formatLayer(EditorState.layers.furniture)};

const decorationLayer = ${formatLayer(EditorState.layers.decorations)};

// Collision Data (0 = walkable, 1 = blocked)
const collisionLayer = ${formatLayer(EditorState.layers.collision)};

// Export Map Data
const MAP_DATA = {
    floor: floorLayer,
    walls: wallLayer,
    furniture: furnitureLayer,
    decorations: decorationLayer,
    collision: collisionLayer
};
`;

    return code;
}

/**
 * Download map as JavaScript file
 */
function downloadMapJS() {
    const js = exportToJS();
    const blob = new Blob([js], { type: 'application/javascript' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = 'map.js';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    updateStatus('Map exported as JavaScript');
}

/**
 * Auto-save to localStorage
 */
function autoSave() {
    try {
        const json = exportToJSON();
        localStorage.setItem('mapEditor_autosave', json);
        localStorage.setItem('mapEditor_autosave_time', new Date().toISOString());
    } catch (error) {
        console.warn('Auto-save failed:', error);
    }
}

/**
 * Load auto-save from localStorage
 */
function loadAutoSave() {
    try {
        const json = localStorage.getItem('mapEditor_autosave');
        const time = localStorage.getItem('mapEditor_autosave_time');

        if (json && time) {
            const shouldRestore = confirm(
                `Found auto-saved map from ${new Date(time).toLocaleString()}.\n\nRestore it?`
            );

            if (shouldRestore) {
                importFromJSON(json);
                updateStatus('Restored auto-saved map');
                return true;
            }
        }
    } catch (error) {
        console.warn('Failed to load auto-save:', error);
    }
    return false;
}

/**
 * Clear auto-save data
 */
function clearAutoSave() {
    localStorage.removeItem('mapEditor_autosave');
    localStorage.removeItem('mapEditor_autosave_time');
}

// Auto-save every 30 seconds
setInterval(() => {
    if (EditorState.hasUnsavedChanges) {
        autoSave();
    }
}, 30000);

// Check for auto-save on load
document.addEventListener('DOMContentLoaded', () => {
    setTimeout(() => {
        loadAutoSave();
    }, 500);
});
